<?php

namespace App\Http\Requests\User;

use Illuminate\Validation\Rule;
use Illuminate\Foundation\Http\FormRequest;

class UserForm extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "email" => [
                'required',
                Rule::unique('users')->ignore($this->id),
                "regex:/(.+)@(.+)\.(.+)/i"
            ],
            "role" => [
                "required",
            ]
        ];
    }
    public function messages()
    {
        //        return parent::messages(); // TODO: Change the autogenerated stub
        return [
            "email.required" => "Bạn chưa nhập Email.",
            "email.regex" => "Đinh dạng Email chưa đúng.",
            "role.required" => "Chưa chọn role"
        ];
    }
}
